ALTER TABLE tarefa ALTER COLUMN descricao SET NOT NULL;
ALTER TABLE tarefa ALTER COLUMN prazo SET NOT NULL;
ALTER TABLE tarefa ALTER COLUMN prioridade SET NOT NULL;
ALTER TABLE tarefa ALTER COLUMN titulo SET NOT NULL;